---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Install python-apt
      shell: apt install python-apt

    - name: Add apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E52529D4

    - name: Add apt repository
      apt_repository:
        repo: deb [ arch=amd64,arm64] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
        state: present

    - name: Update system
      apt:
        update_cache: yes

    - name: Install mongodb-org
      apt:
        name: mongodb-org
        state: present

    - name: Enable MongoDB service
      systemd:
        name: mongod
        enabled: yes
